### ISSUE TITLE
Cmake Xcode project fails

### ISSUE THREAD

**Issue by sphaero** [zeromq/zproject#1200]
Trying to open a zproject library in OSX results in errors ons builds:
```
PhaseScriptExecution CMake\ PostBuild\ Rules libsphactor.build/Debug/sphactor.build/Script-478FADA0B354431F8E16B705.sh
    cd /Users/ect/src/libsphactor
    /bin/sh -c /Users/ect/src/libsphactor/libsphactor.build/Debug/sphactor.build/Script-478FADA0B354431F8E16B705.sh

echo "Creating symlinks"
Creating symlinks
/usr/local/Cellar/cmake/3.14.0/bin/cmake -E cmake_symlink_library /Users/ect/src/libsphactor/Debug/libsphactor.0.0.1.dylib /Users/ect/src/libsphactor/Debug/libsphactor.0.dylib /Users/ect/src/libsphactor/Debug/libsphactor.dylib
CMake Error: failed to create symbolic link '/Users/ect/src/libsphactor/Debug/libsphactor.0.dylib': no such file or directory
CMake Error: cmake_symlink_library: System Error: No such file or directory
CMake Error: failed to create symbolic link '/Users/ect/src/libsphactor/Debug/libsphactor.dylib': no such file or directory
CMake Error: cmake_symlink_library: System Error: No such file or directory
make: *** [sphactor_buildpart_0] Error 1
```

The makefile generated by cmake expects files at certain places which aren't there:
```
# Generated by CMake, DO NOT EDIT
# Custom rules for sphactor
.SUFFIXES: 
all: \
	sphactor_buildpart_0


sphactor_buildpart_0: 
	echo "Creating symlinks"
	/usr/local/Cellar/cmake/3.14.0/bin/cmake -E cmake_symlink_library /Users/ect/src/libsphactor/Debug/libsphactor.0.0.1.dylib /Users/ect/src/libsphactor/Debug/libsphactor.0.dylib /Users/ect/src/libsphactor/Debug/libsphactor.dylib
```
The  /Users/ect/src/libsphactor/Debug/ dir doesn't exist. 

Anybody had success with Xcode?

**Comment by aaronvark** [comment]
I tried to get it to build, and came up with the following:

If I manually create the Debug folder, the symlink creation does not fail. But then the build still fails because it tried to find a file with the name "0.0.1.dylib", instead of the ".dylib" or "0.dylib" files that it has symlinked.

```
Ld osxbuild/Debug/sphactor_selftest normal x86_64
    cd /Users/aoostdijk/Documents/GIT/ECTDev
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-macos10.14 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -L/Users/aoostdijk/Documents/GIT/ECTDev/osxbuild/Debug -F/Users/aoostdijk/Documents/GIT/ECTDev/osxbuild/Debug -filelist /Users/aoostdijk/Documents/GIT/ECTDev/osxbuild/libsphactor.build/Debug/sphactor_selftest.build/Objects-normal/x86_64/sphactor_selftest.LinkFileList -Xlinker -object_path_lto -Xlinker /Users/aoostdijk/Documents/GIT/ECTDev/osxbuild/libsphactor.build/Debug/sphactor_selftest.build/Objects-normal/x86_64/sphactor_selftest_lto.o -Xlinker -no_deduplicate -Wl,-search_paths_first -Wl,-headerpad_max_install_names /Users/aoostdijk/Documents/GIT/ECTDev/osxbuild/Debug/libsphactor.0.0.1.dylib /usr/local/Cellar/zeromq/4.3.2/lib/libzmq.dylib /usr/local/lib/libczmq.dylib -Xlinker -dependency_info -Xlinker /Users/aoostdijk/Documents/GIT/ECTDev/osxbuild/libsphactor.build/Debug/sphactor_selftest.build/Objects-normal/x86_64/sphactor_selftest_dependency_info.dat -o /Users/aoostdijk/Documents/GIT/ECTDev/osxbuild/Debug/sphactor_selftest

clang: error: no such file or directory: '/Users/aoostdijk/Documents/GIT/ECTDev/osxbuild/Debug/libsphactor.0.0.1.dylib'
```

That can be fixed by manually copying the dylib file created by "sudo make install" (into the usr/local/lib/" into the Debug folder and renaming it.

Looks to me like fixing the naming issue would solve the problem. My best guess is xCode generates symlinks for ".dylib" and ".0.dylib", but the CMakeLists.txt uses the SPHACTOR_VERSION (0.0.1) and attempts to find that non-existing file. So, either generate it differently, or get xCode to symlink it correctly?

**Comment by aaronvark** [comment]
Above only helps to run with a previously command-line built dylib, so any changes you make to source code in xCode doesn't translate to an updated .dylib.

In order to work within xCode, replace the reference to the dylib in both the Debug & Release of the "Other Linker Flags" within Linking (Build Settings of any Executable targets), and instead point directly to the generated .a file.

In our specific case, this meant changing:

 ```/Users/aoostdijk/Documents/GIT/ECTDev/osxbuild/Debug/libsphactor.0.0.1.dylib```

to

 ```/Users/aoostdijk/Documents/GIT/ECTDev/osxbuild/libsphactor.build/Debug/sphactor_objects.build/libsphactor_objects.a```

**Comment by aaronvark** [comment]
I tried editing the CMakeListst.txt generated by the "gls project.xml", and I found the following at line 212:

<pre>
IF (MSVC)
  add_library(sphactor SHARED ${sphactor_sources})
ELSE (MSVC)
   add_library(sphactor SHARED $<TARGET_OBJECTS:sphactor_objects>)
ENDIF (MSVC)
</pre>

I've edited this to the following, and that solves all the issues we were having:

<pre>
IF (APPLE)
  add_library(sphactor SHARED ${sphactor_sources})
ELSE (APPLE)
  IF (MSVC)
    add_library(sphactor SHARED ${sphactor_sources})
  ELSE (MSVC)
   add_library(sphactor SHARED $<TARGET_OBJECTS:sphactor_objects>)
  ENDIF (MSVC)
ENDIF(APPLE)
</pre>

Maybe there's a better way to check for both MSVC or APPLE, but this works.

**Comment by sappo** [comment]
Would you like to send a PR?

Aaron Oostdijk <notifications@github.com> schrieb am Do., 26. Sep. 2019,
17:18:

**Comment by aaronvark** [comment]
The above PR is more of a stopgap, and as noted in the comment will fail on some other cases. This might also have something to do with it: https://cmake.org/pipermail/cmake/2016-May/063478.html

**Comment by sphaero** [comment]
We'll open a new issue when we hit that problem
