### ISSUE TITLE
Problem(s): sub-dependencies cannot be conditional on version, and a dependency is always linked against

### ISSUE THREAD

**Issue by bluca** [zeromq/zproject#206]
Hello,

As discussed in https://github.com/zeromq/czmq/pull/1048 I was trying to add a CI target for CMake in Zproject, so that it could be auto-generated, after hard-coding it into CZMQ.

Unfortunately, I do not think it can be done at the moment, and would require one of these two problems to be solved in order to be possible.

1) There is currently no way of making a dependency of a dependency conditional on the dependency version.

The problem is CZMQ and libsodium: when compiling CZMQ against ZMQ < 4, libsodium is not needed. When compiling against ZMQ >= 4, libsodium is needed.

2) There is currently no way of adding a dependency of a dependency that only gets installed (EG: for CI purposes), but not added to the pkg-config check and linked against. As the generator code currently works, the dependency of a dependency is automatically also a dependency. But that is generally not true.

By having the following in zproject_known_projects.xml:

``` xml
    <use project = "zmq"
        repository = "https://github.com/zeromq/libzmq"
        test = "zmq_init"
        cmake_name = "ZeroMQ">
        <use project = "sodium" />
    </use>
```

Sodium becomes a mandatory dependency regardless of the ZMQ version, since CZMQ will always link to it. The problem affects the main build, with autotools (which is not auto-generated on CZMQ), but more importantly with general distribution outside of the CI: if libsodium is added as a dependency, every single build will need it, even if ZMQ < 4.

In my opinion this is conceptually wrong. If CZMQ used symbols from libsodium, then it would be a dependency and it would be linked against. But if it does not use any of the symbols from libsodium, then it should not be linked against it only because ZMQ depends on it. Only ZMQ should link against it.

**Comment by jemc** [comment]
@bluca There are still two separate issues here (as you've outlined).

It is possible to fix the second issue fairly easily.

> 2) There is currently no way of adding a dependency of a dependency that only gets installed (EG: for CI purposes), but not added to the pkg-config check and linked against. As the generator code currently works, the dependency of a dependency is automatically also a dependency. But that is generally not true.

Actually, I've already had to address this when writing the `qt-android` build system.  For every "dependency of a dependency" that is not a direct dependency, the `use.implied` property is defined.  This property can be used to exclude `implied` dependencies by using `for use where !defined (use.implied) [...]` instead of `for use [...]`.

For example:
https://github.com/zeromq/zproject/blob/master/zproject_qt_android.gsl#L41

In general, I agree with you that a project using zproject should specify with `use {library_name}` for every library that they contact directly.  However, I fear that many projects may already be using zproject in a way that is counter to this notion.  Specifically, I think many people may be relying on the guarantee given by [this bit of documentation](https://github.com/zeromq/zproject/blob/master/project.xml#L46).

So, I agree with you that changing the build systems to require explicit `use` for each used library is correct, but it will likely be surprising to some users, so we have to be careful.  I'd like to get input from other stakeholders here.  In particular, @sappo and @hintjens may have some thoughts on the subject.

**Comment by bluca** [comment]
@jemc - thanks for the pointer to use.implied, I had missed it. While we wait for comments from others, I'll have a play with it and see how CZMQ and the CI react when adding that qualifier in the various parts of the build system.

**Comment by hintjens** [comment]
I'd prefer 'use' to match the style of our include system. If we include
'zyre.h' we don't need to also include all its dependencies. This also
covers system libraries, which we try as far as possible to pull in
silently, as needed. I know this doesn't work for everything. Yet where it
does work, it keeps things minimal and safe. The abstraction is valuable
IMO.

**Comment by bluca** [comment]
@hintjens - Ok, I understand your point of view.

Just for curiosity, this is how it would look using @jemc suggestion (use.implied):

Zproject: https://github.com/bluca/zproject/compare/master...bluca:use_implied_build_toolchain
Regen CZMQ: https://github.com/bluca/czmq/commit/e42b8925882adbdec11099f5c286a7df586372ad
Regen CZMQ CI run: https://travis-ci.org/bluca/czmq/builds/73697808

**Comment by bluca** [comment]
Closing as no longer relevant, fixed with project-local hooks
