### ISSUE TITLE
Problem: Cannot identify zeromq sockets by type in bindings

### ISSUE THREAD

**Issue by sappo** [zeromq/zproject#254]
czmq uses void pointers to pass sockets. This is not necessarily the case for bindings as they might wrap zsock or zactor and pass them. IMO it is easiest to add another type named `socket` or `zsocket` to identify socket parameters in the api.

Comments please ;-)

**Comment by sappo** [comment]
@jemc ping

**Comment by jemc** [comment]
I think `socket` would be good, but I'd also be okay with `zsocket`.

**Comment by twhittock** [comment]
Neither work for me. There is already a socket and a zsocket (or at least a
zsock) in my world.

This is a union of types and should be described as such. Possibly an
explicit element which classes define as a local concept.

Alternatively, and I'm not a huge fan of this, but how about an
interface-style name? ISocket? ISendReceive? that sort of construct.
Without turning into Java, ideally.

The organic way zproject is growing makes me worry that this will turn into
a morass unless some structure is put in place soon. It's turning into a
language.

**Comment by jemc** [comment]
I don't have a strong opinion on this issue, as my zproject-bindings-using projects don't typically expose any complex or opaque objects that aren't classes in the library.  That is, I try to make sure most of the API consists of primitives (strings, numbers, etc.).

**Comment by hintjens** [comment]
I think we used 'list', 'hash', etc. to map to zlist, zhash, etc. So it
should be consistent. Thus, 'sock' as the type, if we use it.

I like the notion of an evolving language.

**Comment by twhittock** [comment]
But it isn't just sockets that are accepted, it's actors and other types
too right?

**Comment by jemc** [comment]
@twhittock's point about unions made me think of this point:

I think the biggest issue here is that even adding union type descriptions doesn't get us anywhere here.  Because these functions are supposed to accept a `zsock_t *` or `zactor_t *` or `void *` (zmq socket pointer), right?  So your union description would be something like `sock|actor|anything` and that's no better than simply `anything`.

So really, the best choice here is `anything` (which translates to `void *`).  Higher level language bindings should be generated in such a way that you can pass any kind of pointer to `anything` and any further safety is up to the caller to worry about.

**Comment by jemc** [comment]
If you need more safety than that, you should be using a library that wraps CZMQ to do something specific, and only accepts specific easily bound parameters.

**Comment by sappo** [comment]
As zactors act as zsocks they would be of type `sock` hence we don't need union types and higher-level bindings can pass the wrapper object instead of exposing the wrapped zactor or zsock.

**Comment by Asmod4n** [comment]
In my czmq for mruby wrapper I made a sock_actor type and a special zsock_is which doesn't assert but throws a exception when you pass it something wrong.

**Comment by jemc** [comment]
> As zactors act as zsocks they would be of type sock hence we don't need union types and higher-level bindings can pass the wrapper object instead of exposing the wrapped zactor or zsock.

I think to do this, you'd need a zproject bindings concept of subtypes.

**Comment by hintjens** [comment]
Simplest plausible solution, then?

**Comment by sappo** [comment]
Okay, then the simplest solution would be to identify sockets by name "dest", "output", "source" and "input". Not sure about plausible solution though.

**Comment by hintjens** [comment]
I'm still unclear on the problem here. We pass a void * that the called
method resolves to zsock, zactor, or a zmq socket. This works. Do you want
to remove the variant functionality for bindings? Then you have to generate
multiple methods, or else accept only one, e.g. zsock and force callers to
do the resolution themselves

**Comment by sappo** [comment]
In the Qt bindings I cannot distinct a socket from any other void pointer. Therefore the user pass the wrapped object. For example:
```
QZsock *sock = new QZsock(ZMQ_DEALER);
QZmsg::recv (sock->self);
```
Instead of 
```
QZsock *sock = new QZsock(ZMQ_DEALER);
QZmsg::recv (sock);
```
If I know that a void pointer is actually a socket I can try to resolve to QZsock, QZactor, zsock or zactor.

**Comment by hintjens** [comment]
OK, so we need a type that says, "socket variant". I'd suggest "vsock"...
it's not a class name, it's a virtual socket that maps to one of several
different possible CZMQ classes, using their _is methods.

**Comment by sappo** [comment]
That works for me.

**Comment by jemc** [comment]
@sappo
> In the Qt bindings I cannot distinct a socket from any other void pointer. Therefore the user has to pass the wrapped object.

The autogenerated bindings are always going to have some level of awkwardness when applied to APIs not designed with bindings in mind.  In these cases, I prefer to have a thin hand-written layer on top of the generated layer.  I don't think adding the complexity of special one-off types for these kinds of situations is helpful, but I also can't stop you from doing so :wink:.

**Comment by twhittock** [comment]
For what it's worth, the Python bindings automatically provide the wrapped
pointer when being passed as arguments to wrapped functions. This means
that when a function requests void, it'll be provided, say, a zactor
pointer, which is convertible to void, and everything "just works".

This is accomplished in ctypes by having a field called `_as_parameter_`
which is used when passing an object as a parameter to a ctypes function. A
similar technique could be used for the Qt wrapper I guess.

Still, I'd prefer an api description which describes what rather than how,
personally.

Tom.

**Comment by sappo** [comment]
@jemc true, but sockets are a really essential thing in zeromq ;)

@twhittock I'll have a look at the python bindings maybe I can copy some ideas.

**Comment by hintjens** [comment]
OK, I'm hitting this problem in the nodejs binding. `anything` is unhelpful. I'm using `buffer` for real byte arrays (we can often get/set the size automatically), and for sockets, I propose `sockish`. Any method taking `anything` won't be exposed in the NodeJS binding.

**Comment by sappo** [comment]
`sockish` sound fine for me :+1:
