### ISSUE TITLE
Ruby binding incomplete

### ISSUE THREAD

**Issue by paddor** [zeromq/zproject#288]
Hi

I'm taking another approach at wrapping up a high-level Ruby binding based on the low-level Ruby bindings generated by this project. (https://github.com/paddor/cztop)

I get why the `zchunk_*` functions aren't attached. But is there a reason why the `zauth_*` and `zcert_*` functions aren't attached in the FFI binding?

Also, structs like the `zmq_pollitem_t` (although from libzmq) aren't defined. What's the way to go here? Just asking.

Also, there are no tests. Would it make sense to call all the `z*_test` functions?

**Comment by jemc** [comment]
@paddor - It seems like all of your questions are about CZMQ classes.  Note that zproject bindings generators are general-purpose - they will work for any project that is structured in such a way as to use them.

> I get why the `zchunk_*` functions aren't attached. But is there a reason why the `zauth_*` and `zcert_*` functions aren't attached in the FFI binding?

The classes for which we generate code are the ones for which `api/*.xml` files exist.  Additionally, we only generate code for methods which are listed in the `api/*.xml` files.  People have been writing these for CZMQ as need - so I suppose no one has needed any bindings for `zauth` and `zcert` yet.  If you want to add them, you'll have to write XML models for them and add them to the [`api` directory of CZMQ](https://github.com/zeromq/czmq/tree/master/api) and regenerate with zproject, then file a PR there.

> Also, structs like the `zmq_pollitem_t` (although from libzmq) aren't defined. What's the way to go here? 

We can't define this in zproject, because it doesn't know about the struct.  Moreover, zproject only works for opaque structs right now.  If you wanted to code-generate the wrapper for a transparent struct in zproject, you'd have to devise a way to model it in XML, add a bunch of new code generation features to zproject to support the new model, then add a model for `zmq_pollitem_t` to CZMQ so it would be generated.  Even this is a bit iffy because as you say, the struct is really defined in libzmq.

You could do the above if you had sufficient motivation, but likely the easiest way to make this work would be to treat it as a one-off and simply wrap that struct by hand in your `cztop` library.

> Also, there are no tests. Would it make sense to call all the `z*_test` functions?

Because the bindings are 100% code-generated, I'm not sure what kind of test suite would actually be useful, if any.  I don't think running the C self tests from Ruby is particularly useful, since it's just as easy to run the installed self test binary.  We can't test behavior of generic classes because behavior is effectively arbitrary in the general sense (we don't have it as a part of our model).  We could try to test the "glue" between object and FFI using mocks/stubs, but that's pretty much a waste of time/code/complexity in my opinion, as both the code and tests would be generated from the same model and the same operating assumptions.

**Comment by twhittock** [comment]
The CZMQ Python bindings have hand-written tests to document the usage
scenarios I envisaged, to check the APIs were fully usable in the bound
form, and to help ensure the bindings don't rot over time.

The same rationalle applies to other generated bindings, though as Joe
says, it cannot really be a part of the binding generator itself, as
zproject stands.

The tests in zproject-like projects are also quite interesting as they
constitute a part of the documentation/readme as well as being automated
tests.

I followed the C tests as they were at that time pretty much line for line,
converting the C into Python-ish syntax using regex and fixing up manually.
A random thought: I wonder if it could be possible to create tests in some
manner which allowed them to become more useful documentation, and to allow
automatic generation of the tests for the various bindings as well as the C
code?

**Comment by jemc** [comment]
> I wonder if it could be possible to create tests in some manner which allowed them to become more useful documentation, and to allow automatic generation of the tests for the various bindings as well as the C code?

I'm skeptical it can be done in a general way, but if you have the ideas and motivation to implement it (without making zproject any less general), then I don't want to hold you back! :grin:

**Comment by hintjens** [comment]
Could be done using a separate model, and IMO would be useful. See my
article on ending software versions... http://hintjens.com/blog:85

**Comment by paddor** [comment]
AFAICS, it's complete now. And it's available in a new gem called _czmq-ffi-gen_.

* on [github](https://github.com/paddor/czmq-ffi-gen)
* on [rubygems](https://rubygems.org/gems/czmq-ffi-gen)
* on [rubydoc](http://www.rubydoc.info/gems/czmq-ffi-gen)
