### ISSUE TITLE
Problem: constructors don't have defaults

### ISSUE THREAD

**Issue by hintjens** [zeromq/zproject#378]
This problem arose in the JNI binding. I need to create a class instance in order to run tests, yet I've no sane defaults to pass a constructor.

Solution: allow every argument in a constructor to be null (or zero for integers) and require that the _new method deal with this sanely. Further, put this into CLASS as a requirement.

What do we think?

**Comment by paddor** [comment]
Would this apply even for the non-`new()` constructors like `zconfig_load(filename)`?

**Comment by hintjens** [comment]
It doesn't matter for those, really. Semantically it's to be able to always
generate a constructor with no arguments.

**Comment by Asmod4n** [comment]
Out of the top of my head i know two semantics for something like this.

In some languages you can define default values for arguments and in others you can override functions based on how many arguments there are.

In both cases you can set default arguments based on how many are passed...

But this seams a bit too much for CLASS, or?

**Comment by jemc** [comment]
@hintjens 

I'm wary of imposing that kind of restriction on the implementation of all zproject constructors.

I don't remember what thread it was, but someone was suggesting that we add an additional dialect of our modeling language that describes tests, so that tests could be generated in each language.  I think that's a pretty ambitious project, but I think we could do a small subset of this to fix your problem.

Instead of imposing restrictions on the implementation of constructors (which sometimes may have good reasons for requiring real objects/data to be initialized?), why not describe in our modeling language what arguments to pass for a "default" instance to be constructed?  This would include both simple literal values (like numbers) or "nested" objects (which would themselves be constructed from literals and "nested" objects).  We may be able to make something like that clean.

Out of curiosity, what specifically are you trying to test here?  We've had discussions about generating test code for the generated class code in the past, but I've yet to be convinced that it's a good idea.  In the past, I've always used handwritten tests to confirm things that I needed to confirm, but in general just relied on the consistency of generated code to be correct.

**Comment by hintjens** [comment]
The problem I faced was, first I need a class instance to run tests. Second, I don't know how to generate that for constructors that take arguments (like zactor, for instance). Third, I solve that by creating void constructor if needed. Fourth, people try to use those void constructors for real work, and they crash.

**Comment by jemc** [comment]
But what is it that you're testing, if the zproject generator doesn't understand anything about the meaning of the class or what it does?

I don't think we need to automate tests for generated code when we can't test anything meaningful.

**Comment by hintjens** [comment]
I'm calling the _test method of the class, which is fine and meaningful.
Just can't call it without a class instance (even for classes like zstr).

**Comment by jemc** [comment]
@hintjens - The `_test` method should be a singleton - does Java not have a concept of singleton/class methods (methods that by definition don't require a class instance)?

**Comment by jemc** [comment]
Looks like the concept does exist in Java - http://www.fredosaurus.com/notes-java/flow/methods/50static-methods.html

**Comment by jemc** [comment]
The invocation should look like: 
```java
ZStr.test()
```

**Comment by paddor** [comment]
Funny. I just implemented very basic tests for all Zclasses in the new _czmq-ffi-gen_ gem yesterday and had pretty much the same problem. At least calling the `_test` function was easy, as it's a singleton. But to test the boilerplate code Ruby code, I wanted to have an instance of each Zclass. But some of them need to be instanciated differently or don't provide the `_print` method which would serve as a simple way to test whether the pre-conditional nullpointer check works. [Shared test examples](https://github.com/paddor/czmq-ffi-gen/blob/master/spec/czmq-ffi-gen/czmq/ffi/spec_helper.rb)

I factored instanciating an object and calling a simple method on it into `zobj` and `use_pointer`, respectively. [Zarmour](https://github.com/paddor/czmq-ffi-gen/blob/master/spec/czmq-ffi-gen/czmq/ffi/zarmour_spec.rb) [Zlist](https://github.com/paddor/czmq-ffi-gen/blob/master/spec/czmq-ffi-gen/czmq/ffi/zlist_spec.rb) [Zstr](https://github.com/paddor/czmq-ffi-gen/blob/master/spec/czmq-ffi-gen/czmq/ffi/zstr_spec.rb) [Zmsg](https://github.com/paddor/czmq-ffi-gen/blob/master/spec/czmq-ffi-gen/czmq/ffi/zmsg_spec.rb) [Zsock](https://github.com/paddor/czmq-ffi-gen/blob/master/spec/czmq-ffi-gen/czmq/ffi/zsock_spec.rb)

(Zstr is actually the only one that cannot be instanciated and thus have no constructor and no instance methods.)

**Comment by hintjens** [comment]
@jemc, thanks, this will fix the issue for JNI.
