### ISSUE TITLE
Problem: unclear how to resolve dependencies

### ISSUE THREAD

**Issue by hintjens** [zeromq/zproject#395]
Currently, zproject looks in /usr/local/share/zproject for class files. This is nasty for a few reasons:

* It's not portable
* It assumes we make/install dependencies beforehand
* It creates copies of the class files which can sometimes confuse things (e.g. if you're trying to resolve a class)
* We can't extend to other bits of a project (my problem is how to copy MSVC property files between projects)

I'd like a general solution that lets us use anything from dependent projects, if we use a standard fixed structure. So e.g. always builds/android and builds/msvc.

If we assume/require that dependent projects live in the same directory tree, as siblings, we can find files explicitly, e.g. "../$(use.project)/api/$(class.name).xml"

What do we think of this?

**Comment by sappo** [comment]
I agree with you about the nastiness. Especially having copies of api files installed. Requiring that dependent projects live in the same directory works fine for me and my workflow! 

Maybe we can work with environment variables to lift the same directory requirement but this might be nasty as well.

**Comment by hintjens** [comment]
The same parent directory requirement seems sane, for a development machine.

**Comment by sappo** [comment]
Sure, lets keep things simple!

**Comment by jemc** [comment]
I see the proposed solution as having a mix of advantages and disadvantages over the current one.  They both seem roughly equally problematic to me, to be honest.

I'm okay with requiring the same parent directory, I think, but I'm not sure about requiring the project name to be the folder name - sometimes repositories in work folders need extra layers of disambiguation for various reasons, so the name of the repository might not always match the zproject-known project name.  For example, `libzmq` is the repository for the `zmq` project while `czmq` is the repository for the `czmq` project.  These are both reasonable conventions for projects, and there may be others.  Note that `libzmq` doesn't have zproject models, so this is not a big deal, but other user projects might use the same convention.

That said, this doesn't cause any direct problems for any of my projects at the moment.  So I'm okay with going this route until I have a concrete problem on my hands.  If/when I do, I'll probably enhance zproject to use environment variables to override, as @sappo suggested.  This is similar to how the `android` build system works.

@hintjens - However, just a quick back-track for a moment on the problem you have: 

> We can't extend to other bits of a project (my problem is how to copy MSVC property files between projects)

If these MSVC property files are generated by zproject, and you have access to the `project.xml` and `api/*.xml` files of the other project, isn't it possible to use zproject to regenerate these files where you need them, instead of copying them?

**Comment by hintjens** [comment]
Regenerating the files would then be possible, yes. It's more work.

**Comment by hintjens** [comment]
I've started using this approach in the MSVC builds.

**Comment by hintjens** [comment]
Closing and rewriting this.
