### ISSUE TITLE
Problem: I want to break existing APIs

### ISSUE THREAD

**Issue by hintjens** [zeromq/zproject#455]
Specifically, zmsg_encode and zarmour_encode.

The problem is both these are shipped in stable releases of CZMQ and so are untouchable. I'd like to change our rules. I'm pretty sure both these methods count as "unstable".

Solution: start to tag classes and methods with stability status. Here's my proposal:

* All untagged classes and methods are by definition "draft," meaning they are open to change even if they are released in stable releases of the project.
* A class can have 'state = "stable"' to indicate that its API is now being used in production. That freezes it.
* Individual methods can override the class state with their own 'state = "draft"' if they are newly added to a stable class.
* 'state = "deprecated"' at the class or method level marks deprecated classes or methods.

The tagging is mainly for documentation purposes. That is, we can generate warnings like "This piece of the API is unstable and subject to change."

**Comment by bluca** [comment]
Hi,

First of all, I completely understand the frustration that sometimes can arise when realizing an API could get a nice improvement, but it has implications for the API "contract" that makes a simple step very complicated.

Unfortunately speaking as the Debian (and Ubuntu I guess, since it's pulled straight from Debian to Universe) CZMQ maintainer, I'm afraid distributions wouldn't be able to make good use of such a scheme.

If an API is public and exposed as a symbol, then if it changes the soname must be bumped and more importantly I _must_ release a new version of the -dev package (eg: libczmq4-dev), and then slowly proceed to send patches to all dependents to build against the new version. If I simply do a new upload with the same soname version and package name, builds are going to fail, applications and packages are going to break, and I'm going to be yelled at, and rightly so :-)

Usually APIs are not exposed at all until deemed stable, and live in a dev branch until then. To get around this, what if, for future new symbols, APIs in "draft" state are hidden behind an \#ifdef in the header managed by an autoconf/cmake flag (eg: --disable-draft-api)? This way, as a maintainer, I can upload packages only with the stable API exposed, and distribution users that have more advanced needs and want to experiment with draft APIs can easily rebuild themselves, either from the package source or straight from upstream.

**Comment by hintjens** [comment]
I like the idea of only publishing stable symbols. Very neat! This solves the problem (not for the two cases here, which are historical) but for future cases. And we have the tooling to do this now... 

* Building from git -> get all methods.
* Building from stable release -> get only stable methods.
* Once tagged stable, a method CANNOT be changed.

We can introduce this with ṫhe next major ABI version IMO, and then we can in fact make the breaking changes as well...

I'm going to summarize the solution:

* All methods are considered unstable unless tagged "stable" or "deprecated"
* Tarballs and stable releases only contain stable and deprecated methods.
* Builds made from git master contain all methods.

**Comment by jemc** [comment]
Cool solution!

**Comment by Asmod4n** [comment]
:+1:

**Comment by paddor** [comment]
Sounds really good.

But can I ask why those two functions count as unstable?

**Comment by hintjens** [comment]
They're not unstable as such, just problematic.

These are two that I spotted when reviewing the API. They return buffers
via two routes; return value and argument-by-reference. I could not make
them work properly for the JNI binding. After some thought I realized, they
should return zchunk objects.

There are surely other functions that need fixing as well.

I'd like to allow classes time to mature, which can be months, even a year.
During that time we need also to make stable releases. Today, a stable
release fixes all methods, even recent ones that haven't matured.

**Comment by bluca** [comment]
Would it be possible to do an API review of CZMQ, and break what needs to be broken all at once in the same release? It would make the life of us downstream maintainers sooo much easier :-)

**Comment by hintjens** [comment]
Great idea. We can remove the deprecated methods and classes too, maybe.

**Comment by bluca** [comment]
Yes if the intention for deprecated stuff is to be removed entirely, if would be great if it's all done in the same release :-)
