### ISSUE TITLE
Problem: no way to mark enum items as DRAFT

### ISSUE THREAD

**Issue by bluca** [zeromq/zproject#460]
I raised this point in the PR I sent yesterday, but I feel an issue is more appropriate to avoid losing track.

How should we deal with individual draft elements inside enums?

A first thought was just to loop first over the stable elements of an enum, and the over the unstable ones, like for the other stuff. But that means once an unstable becomes stable, the relative positions change and the ABI is broken.

Would it be acceptable if we enforce when parsing the XML that draft elements in an enum must always go after the stable ones, and fail to generate if not?

The PR I sent yesterday doesn't consider the state of the individual elements, I left it out for this reason.

**Comment by hintjens** [comment]
I wanted to kill enums in fact, as they add a lot of complexity for little benefit (the syntax is so specific)….

I'd prefer to use constants, as that lets us rename and deprecate enums with poorly chosen names (as we've done for ZMQ socket types over time).

We could still use an abstract type in the API model so that the documentation for a method lists possible values for arguments.

**Comment by bluca** [comment]
Ah that's even better, one less thing that can break ABI. Feel free to close this then (or maybe it can be closed when the support for enums is pulled).

**Comment by jemc** [comment]
+1 to constants over enums

**Comment by hintjens** [comment]
OK, I'm removing these in CZMQ and Zyre, and will deprecate the functionality in zproject.

**Comment by bluca** [comment]
:+1:
