### ISSUE TITLE
Problem: zproto does not play well with API files

### ISSUE THREAD

**Issue by sappo** [zeromq/zproject#490]
My suggestion would be the generate the API models after zproject is done. Is this possible with gsl?

**Comment by hintjens** [comment]
I'll make it work. Give me a few minutes .

**Comment by sappo** [comment]
@hintjens take your time :-)

**Comment by hintjens** [comment]
So to clarify the problems here, as "does not play well" is kind of vague:

* zproto does not use zproject for installation (this is minor and I think not worth fixing)
* C client and server APIs for e.g. Malamute are output as .h and not as .xml.
* C codecs APIs are similarly output as .h and not as .xml

The change I'll make is:

* Add a switch to generate API XML model instead of .h for these three cases

Then zproject can use this switch (since it generates the calls to zproto). Existing projects won't be affected.

**Comment by sappo** [comment]
:+1:

**Comment by hintjens** [comment]
Fixed for proto and client (not for server, yet).

**Comment by sappo** [comment]
I'll give it a try tomorrow, thanks.
Am 31.01.2016 5:58 nachm. schrieb "Pieter Hintjens" <
notifications@github.com>:

**Comment by sappo** [comment]
With #519 #520  and zeromq/zproto#300 proto and client work fine for me.
