### ISSUE TITLE
Generated files are in Git

### ISSUE THREAD

**Issue by eburkitt** [zeromq/zproject#667]
There are a few generated files that are part of the project repo. Is this an oversight or is there a reason they have been left in?

If they are dispensable I will submit a PR to remove them.

-evan

**Comment by hintjens** [comment]
Probably an oversight but some generated files need to be there to build a
freshly cloned repo.

**Comment by bluca** [comment]
Which does are you referring to?

**Comment by jemc** [comment]
Note that it is zproject-idiomatic to include a lot of generated files in revision control.  This is because much of your project structure is generated by zproject, and you usually don't want to require users of your library to install and use zproject to be able to build and install your library.

**Comment by hintjens** [comment]
In older iMatix projects we were a lot stricter about never putting generated code under source control. This policy seems smart yet it's actually quite counter-productive. I'll recap the main sources of pain:

* It forces beginners (who just want to get the repo, build it, try it) to learn an entirely separate tool chain.
* It forces distributions to provide bootstrapping binaries (e.g. for gsl, the code generator) since even gsl did not used to compile until you'd regenerated it.
* It assumes there's a clear layer distinction between "generated" and "hand-written" when realistic projects can mix and match; e.g. a .c file might be generated yet appear to be hand-written so that it fits into an existing build/documentation process.
* It assumes that versioning generated files is somehow negative when in fact it's not.

The main lessons we learned (quite painfully, over many years) were:

* Don't put the generation date into generated files.
* Ensure that a clean checkout/clone can build as-is without any bizarro bootstrapping.
* Hide the very fact of code generation from beginning users, and expose this later on a need-to-know basis.
* Don't put build outputs into the repo (e.g. files that make or cmake generates).

**Comment by eburkitt** [comment]
The files I was thinking to remove were CMakeLists.txt, Makefile.am and configure.ac. The idea came from the fact that, not only did running `gsl projects.xml` for zproject generate them all, but the generated CMakeLists.txt is different from the one in Git. This lead me to imagine that the files had been put into the repo by mistake or oversight and that I should be the one to rectify the problem. After reading your replies and taking a deep breath I've come to my senses. While all programmers may possess the _traits_ of laziness, impatience and hubris, only in great programmers are they virtues. :)>
